config/routes.rb
Rails.application.routes.draw do
  get 'stock/index'
  post 'stock/index'
  post 'stock/ajax_regist_mylist'
  post 'stock/add_stock_mylist'
  post 'stock/ajax_disp_chart'

  get 'my_list/index'

  get 'chart/index'
  post 'chart/index'
  post 'chart/ajax_delete_from_mylist'

  get 'title/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mylist.rb
class Mylist < ApplicationRecord
    has_many :mylist_stocks
    has_many :stocks, through: :mylist_stocks
end

app/models/mylist_stock.rb
class MylistStock < ApplicationRecord
    belongs_to :mylist
    belongs_to :stock
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :trading_view
end

app/models/trading_view.rb
class TradingView < ApplicationRecord
    belongs_to :stock
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chart_controller.rb
class ChartController < ApplicationController
  def index
    if params[:time_id].present?
      @time_id = params[:time_id].to_i
      @time = "D" if @time_id == 2
      @time = "W" if @time_id == 3
      @time = "M" if @time_id == 4
    else
      @time = "W"
    end

    @mylists = Mylist.all
  end

  def ajax_delete_from_mylist
    stock_id = params[:stock_id]
    mylist_id = params[:mylist_id]

    mylist = MylistStock.find_by(mylist_id: mylist_id, stock_id: stock_id)
    mylist.destroy if mylist.present?
  end
end

app/controllers/my_list_controller.rb
class MyListController < ApplicationController
  def index
    @stocks = Stock.all
  end
end

app/controllers/stock_controller.rb
class StockController < ApplicationController
  def index
    search_param = params[:search]

    if search_param.present?
      @stocks = Stock.where('code like ? or client_name like ? or explain like ?', "%" + search_param + "%", "%" + search_param + "%", "%" + search_param + "%")
    else
      @stocks = Stock.all
    end

    @stocks = @stocks.page(params[:page]).per(20)
    @mylists = Mylist.all
  end

  def ajax_regist_mylist
    @mylist = Mylist.create({name: params[:list_name]})
    @stock_id = params[:stock_id]
  end

  def add_stock_mylist
    @mylist_id = params[:mylist_id]
    @stock_id = params[:stock_id]
    MylistStock.create({mylist_id: @mylist_id, stock_id: @stock_id})
    render json: {error_flg: false}
  end

  def ajax_disp_chart
    @stock = Stock.find_by(id: params[:stock_id])
    @trading_view = TradingView.find_by(stock_id: @stock.id)
    @symbol_code = @stock.code
    @container_id = @trading_view.container_id
    @time = "W"
    render template: "shared/_tradingview", layout: false
  end
end

app/controllers/title_controller.rb
class TitleController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chart_helper.rb
module ChartHelper
end

app/helpers/my_list_helper.rb
module MyListHelper
end

app/helpers/stock_helper.rb
module StockHelper
end

app/helpers/title_helper.rb
module TitleHelper
end

app/views/chart/index.html.erb
<div class="chart-selectbox-group">
    <%= form_tag({ :controller => "/chart", :action => "index" },{ :id => "select_form_id"}) do %>

        <%# select_tag("select_mylist", options_for_select(@mylists.pluck(:name))) %>

        <div class="">
            <select id="time_id" name="time_id" class="time-select" onchange="this.form.submit()">
                <option value="2" <%= @time_id == 2 ? "selected" : "" %>>日足</option>
                <option value="3" <%= @time_id == 3 ? "selected" : "" %>>週足</option>
                <option value="4" <%= @time_id == 4 ? "selected" : "" %>>月足</option>
            </select>
        </div>
    <% end %>

    <select class="grid-select">
        <option value="1">〓</option>
        <option value="2">■■■</option>
    </select>
</div>

<% @mylists.each do |mylist| %>
    <h2 class="mylist"><%= mylist.name %></h2>
    <div class="chart-area">
        <% TradingView.where(stock_id: mylist.stocks.pluck(:id)).each do |tradingview| %>
            <% unless tradingview.nil? %>
                <div class="blog-card">
                    <%= render :partial => "shared/tradingview", locals: { symbol_code: tradingview.code, container_id: tradingview.container_id, time: @time} %>
                    <%= image_tag 'resize.png', class: "icon-resize" %>
                    <div class="btn-circle-3d" data-stockid="<%= tradingview.stock_id %>" data-mylistid="<%= mylist.id %>"><%= image_tag 'trash.png', class: "icon-trash" %></div>
                </div>
            <% end %> 
        <% end %> 
    </div>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>米株を探そう！</title>
    <link rel="shortcut icon" href="favicon.png" type="image/png">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render :partial => "shared/header" %>
    <%= render :partial => "shared/menu" %>

    <div class="container">
      <%= yield %>

      <%= render :partial => "shared/footer" %>
    </div>
  </body>

</html>

app/views/my_list/index.html.erb
<h1>MyList#index</h1>
<p>Find me in app/views/my_list/index.html.erb</p>

app/views/shared/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/shared/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= image_tag 'machine.jpg', id: "icon-header", class: "image" %>
      <%= link_to "america stocks - analytics", '#', id: "logo" %>
    </div>
  </div>
</header>

app/views/shared/_menu.html.erb
<div class="menu">
  <nav>
    <ul>
      <li class="menu-disp"><a data-turbolinks="false" href="<%= chart_index_path %>"><%= image_tag 'chart.png', class: "icon-menu" %> Chart</a></li>
      <li class="menu-disp"><a data-turbolinks="false" href="<%= stock_index_path %>"><%= image_tag 'stocks.png', class: "icon-menu" %> stocks</a></li>
      <li class="menu-disp"><a data-turbolinks="false" href="<%= my_list_index_path %>"><%= image_tag 'list.png', class: "icon-menu" %> MyList</a></li>
    </ul>
  </nav>
</div>

app/views/shared/_tradingview.html.erb
<% symbol_code = "NASDAQ:AAPL" if symbol_code.nil? %>
<% container_id = @container_id if @container_id.present? %>
<% symbol_code = @symbol_code if @symbol_code.present? %>

<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
  <div id="<%= container_id %>" style="height: 100%;"></div>
  <div class="tradingview-widget-copyright">TradingView提供の<a href="https://jp.tradingview.com/symbols/<%= symbol_code %>/" rel="noopener" target="_blank"><span class="blue-text">AAPLチャート</span></a></div>
  <script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
  <script type="text/javascript">
  new TradingView.widget(
  {
  "autosize": true,
  "symbol": "<%= symbol_code %>",
  "interval": "<%= @time %>",
  "timezone": "Etc/UTC",
  "theme": "dark",
  "style": "1",
  "locale": "ja",
  "toolbar_bg": "#f1f3f6",
  "enable_publishing": false,
  "allow_symbol_change": true,
  "container_id": "<%= container_id %>"
}
  );
  </script>
</div>
<!-- TradingView Widget END -->

app/views/shared/_tradingview2.html.erb
<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
  <div id="tradingview_d84c3"></div>
  <div class="tradingview-widget-copyright">TradingView提供の<a href="https://jp.tradingview.com/symbols/MIL-B/" rel="noopener" target="_blank"><span class="blue-text">Bチャート</span></a></div>
  <script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
  <script type="text/javascript">
  new TradingView.widget(
  {
  "autosize": true,
  "symbol": "MIL:B",
  "interval": "D",
  "timezone": "Etc/UTC",
  "theme": "dark",
  "style": "1",
  "locale": "ja",
  "toolbar_bg": "#f1f3f6",
  "enable_publishing": false,
  "allow_symbol_change": true,
  "container_id": "tradingview_d84c3"
}
  );
  </script>
</div>
<!-- TradingView Widget END -->

app/views/stock/ajax_regist_mylist.js.erb
$('#mylist-list').append("<p class='add-list' data-stockid='<%= @stock_id %>' data-mylistid='<%= @mylist.id %>'><%= @mylist.name %></p>")

app/views/stock/index.html.erb
<input type="hidden" id="stock">

<div id="stock-header">
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <%= form_tag({ :controller => "/stock", :action => "index" },{ :id => "search_form_id", :class => "search_container"}) do %>
    <input type="text" name="search" size="25" placeholder="銘柄コード, 会社名, 説明を入力">
    <input type="submit" value="&#xf002">
  <% end %>

  <svg xmlns="http://www.w3.org/2000/svg" version="1.1">
    <defs>
        <filter id="gooey">
            <!-- in="sourceGraphic" -->
            <feGaussianBlur in="SourceGraphic" stdDeviation="5" result="blur" />
            <feColorMatrix in="blur" type="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 19 -9" result="highContrastGraphic" />
            <feComposite in="SourceGraphic" in2="highContrastGraphic" operator="atop" />
        </filter>
    </defs>
  </svg>

  <button id="gooey-button">
    <%= image_tag 'movie.png', class: "icon-movie" %>
    <div class="slide-load"></div>
    <span>slide-show</span>
    <span class="bubbles">
        <span class="bubble"></span>
        <span class="bubble"></span>
        <span class="bubble"></span>
        <span class="bubble"></span>
        <span class="bubble"></span>
        <span class="bubble"></span>
        <span class="bubble"></span>
        <span class="bubble"></span>
        <span class="bubble"></span>
        <span class="bubble"></span>
    </span>
  </button>
</div>

<div id="stock-chart">
  <%= image_tag 'smile.png', class: "icon-chart-ast" %>
  <div class="loader001"></div>
  <div id="chart_container"></div>
</div>

<table class='table-stocks'>
    <tr class='table-index-th'>
        <th class="first"></th>
        <th>銘柄コード</th>
        <th>企業名</th>
        <th style="width: 50%">説明</th>
        <th class="last">市場</th>
    <tr>
    <% @stocks.each do |stock| %>
        <tr class='table-index-tr' data-stockid="<%= stock.id %>", data-href="https://www.tradingview.com/chart/aiKNXGel/?symbol=<%= stock.market + "%3A" + stock.code %>" target="_blank">
            <td><%= image_tag 'machine.jpg' %></td>
            <td><%= stock.code %></td>
            <td><%= stock.client_name %></td>
            <td><%= stock.explain %></td>
            <td><%= stock.market %></td>
        </tr>
    <% end %>
</table>

<%= paginate @stocks %>

<div id="mylist-dropdown">
  <p class="astarisk">ESCで閉じる</p>
  <a href="javascript void(0)" id="trd-idea-link" target="_blank"><p>アイディアを見る</p></a>
  <p class="astarisk">My List</p>
  <div id="mylist-list">
    <% @mylists.each do |mylist| %>
      <p class="add-list" data-stockid="" data-mylistid="<%= mylist.id %>"><%= mylist.name %></p>
    <% end %>
  </div>
  <p class="astarisk">リスト新規</p>
  <p class="list_name_label">名前</p>
  
  <%= form_tag({:controller => '/stock', :action => 'ajax_regist_mylist'}, :remote => true, :class => 'form-ajax') do -%>
    <input type="text" name="list_name" size="25" placeholder="リスト名"　id="list_name_input">
    <input type="hidden" name="stock_id" value="" id="stock_id_for_id">
    <input type="submit" value="登録">
  <% end %>
</div>

app/views/title/index.html.erb
<div class="container">
  <ul class="timeline">
    <li class="timeline-inverted">
      <div class="timeline-badge success"><i class="glyphicon glyphicon-thumbs-up"></i></div>
      <div class="timeline-panel">
        <div class="timeline-heading">
          <h4 class="timeline-title">Mussum ipsum cacilds</h4>
        </div>
        <div class="timeline-body">
			<blockquote class="twitter-tweet" data-theme="light"><p lang="ja" dir="ltr">今週の注目株①6315.TOWA<br><br>半導体製造関連装置大手。上方修正で上昇も、直近は地合いとトヨタ減産の連れ安で下落中（予想）<br><br>テクニカル的には上方で急騰＆最高出来高をつけた7月30日の価格帯まで全戻しし、25MA比-2%、75MA比+4%と節目感強い印象。今週どんな展開になるのか注目したい。 <a href="https://t.co/1uYBv2ZrEt">pic.twitter.com/1uYBv2ZrEt</a></p>&mdash; タカニキ@金持ち戦略ch (@make_life_rich) <a href="https://twitter.com/make_life_rich/status/1429272298687631366?ref_src=twsrc%5Etfw">August 22, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
			
        </div>
      </div>
      <div class="chart-view">
	  	<%= render :partial => "shared/tradingview" %>
      </div>
    </li>
  </ul>
</div>